services:
  postgres:
    image: postgres:16-alpine
    container_name: portfo_db
    environment:
      POSTGRES_DB: portfo_db
      POSTGRES_USER: user_db
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: